### ISSUE TITLE
Impossible d'installer sous MacOS 10.13.2

### ISSUE THREAD

**Issue by MacDamien** [c4software/bepo_developpeur#2]
Bonjour,

Je ne vois que des .bundle dans le dossier /Bibliothèque/Keyboard Layouts/ de la racine du disque : le bépo un bépo russe que j'ai fabriqué avec Ukelele. Et quand je glisse le bepoDev.keylayout, et que je redémarre, les préférences clavier ne voit rien.
Comme ça me plairait bien de ne pas tout refaire à la main, je voulais savoir si tu avais l'idée d'une solution.

**Comment by c4software** [comment]
C’est étrange. Tu as d’autres chose dans le dossier ```/Bibliothèque/Keyboard Layouts/``` moi je n’ai que : 

![capture d ecran 2018-01-07 a 21 58 59](https://user-images.githubusercontent.com/988914/34654040-12a7c37c-f3f6-11e7-8757-e68bda59f08d.png)

Attention également la méthode de saisie est dans Autres : 

![capture d ecran 2018-01-07 a 22 00 20](https://user-images.githubusercontent.com/988914/34654056-39b5fe70-f3f6-11e7-9935-794bb2409b48.png)

**Comment by MacDamien** [comment]
Bon, je regarde ça plus tard, merci. —Damien Vanneuville07.01.2018, 22:01, "Brosseau Valentin" <notifications@github.com>:C’est étrange. Tu as d’autres chose dans le dossier /Bibliothèque/Keyboard Layouts/ moi je n’ai que :

Attention également la méthode de saisie est dans Autres :

**Comment by MacDamien** [comment]
Bonjour,

J’ai fait le vide pour n’y laisser que le bépodev, Ça ne fonctionne pas (pas de bépo dans la recherche).
Le fichier téléchargé avait l’extension .html après .keylayout. J’ai supprimé cette extension.

voilà…

Il me semble que j’avais déjà eu le problème, n’est-ce pas mieux accepté dans un bundle ? en tout cas, ça ne marche pas de le glisser dans mon bundle bépo, il doit manque une référence à indiquer dans un sommaire.

bonne journée,





--
Damien Vanneuville

**Comment by c4software** [comment]
Intéressant le .html à la fin. Tu as du enregistrer le mauvais fichier (ou ton navigateur l’a modifié en cours de route)

Tu as bien enregistré le fichier : https://raw.githubusercontent.com/c4software/bepo_developpeur/master/osx/bepoDev.keylayout

Sinon tu peux faire dans un terminal, pour être certains que le fichier ne soit pas modifié.

```sh
wget https://raw.githubusercontent.com/c4software/bepo_developpeur/master/osx/bepoDev.keylayout
```

Pour le bundle normalement ça ne change rien (c’est juste un packaging).

**Comment by MacDamien** [comment]
Parfait, c’est résolu.

Wget le fait mieux que Safari.
Ça me motive à retoucher mon bépo-russe-phonétique, du coup.

Merci.
