### ISSUE TITLE
Disposition non reconnue dans le switcher

### ISSUE THREAD

**Issue by hakimilg** [c4software/bepo_developpeur#3]
Bonjour (et merci pour le travail effectué).
Je suis sous Ubuntu 21.10 (Gnome 40)
J'ai bien réussi à installer la disposition via le script (et je la trouve dans l'interface qui permet de rajouter un layout), en revanche, je ne peux pas la sélectionner. Dans le sélecteur de disposition, elle n'apparaît pas.
Je reste disponible s'il faut des informations complémentaires. Je ne sais pas si ça peut être lié au fait que je suis sur une sessions Wayland

**Comment by c4software** [comment]
Bonjour,

Intéressant comme problème. Je vais regarder avec un ISO live pour voir si je reproduit le problème. As-tu tenter une déconnexion / reconnexion après l'ajout de la disposition ?

PS: Perso j'utilise Archlinux (mais de mémoire, je n'avais pas rencontré de problème avec Pop_OS!)

**Comment by hakimilg** [comment]
Punaise, je ne suis pas malin, c'est pourtant la base. En redémarrant le PC ce matin, elle apparaît bien. Désolé pour le dérangement

**Comment by c4software** [comment]
Parfait alors ! Je vais ajouter une note dans le README
